version: "3.9"
services:
    mysql:
        image: mysql:latest
        container_name: dbEvent
        # Uncomment below when on Mac M1
        # platform: linux/arm64/v8
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql  # Persist MySQL data
        ports:
            - 34306:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 8090:8080
    # MAILPIT
    mailpit:
        image: axllent/mailpit
        container_name: laravel-exa-mailpit
        ports:
            - 1025:1025
            - 8025:8025

#version: '3'
#
#services:
#    mysql:
#        image: mysql:latest
#        container_name: mysql_container
#        ports:
#            - "33306:3306"  # Map the MySQL container's port to your host machine
#        environment:
#            MYSQL_ROOT_PASSWORD: root5root
##            MYSQL_DATABASE: root
##            MYSQL_USER: root
##            MYSQL_PASSWORD: root5root
#        volumes:
#            - mysql_data:/var/lib/mysql  # Persist MySQL data
#
volumes:
    mysql_data:
